import Head from "next/head";
import Image from "next/image";
import CategoriesBar from "../components/CategoriesBar";
import HeroBanner from "../components/HeroBanner";
import Product from "../components/Product";
import ProductFull from "../components/ProductFull";
import {
  fetchBanner,
  fetchCategories,
  fetchProducts,
  fetchProductSlug,
} from "../http";

export default function Home({ categories, products, banner, productData }) {
  // console.log(products.items.data[0]);
  // console.log(banner.items.data.attributes);
  // console.log(categories);
  console.log(productData);
  const allProduct = products.items.data;
  const singleProduct = products.items.data[0];
  return (
    <div>
      <Head>
        <title>Hello guys</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="py-4">
        <HeroBanner heroBanner={banner} />
        <CategoriesBar categories={categories} />
        <div className="my-3 text-center ">
          <h3 className="fw-bold colorSlate">Newly Launched Product</h3>
          <p className="text-secondary">Available in each category</p>
        </div>
        <div className="d-flex align-items-center justify-content-evenly flex-wrap">
          {allProduct.map(function (data) {
            return <Product data={data} />;
          })}
          {/* <Product data={singleProduct} /> */}
        </div>
        <hr />
        <div>
          <ProductFull />
        </div>
        <hr />
      </main>
    </div>
  );
}

export const getServerSideProps = async () => {
  //categories,products will be fetched here
  const data = await fetchCategories();
  const products = await fetchProducts();
  const banner = await fetchBanner();
  const productFullDetails = await fetchProductSlug(
    `infinix-hot-12-pro-electric-blue-128-gb-8-gb-ram-1`
  );
  return {
    props: {
      categories: {
        items: data.data,
      },
      products: {
        items: products.data,
      },
      banner: {
        items: banner.data,
      },
      productData: {
        items: productFullDetails.data,
      },
    },
  };
};
